# Configuration settings for EDA Tool

# Analysis thresholds
OUTLIER_ZSCORE_THRESHOLD = 3
OUTLIER_IQR_MULTIPLIER = 1.5
HIGH_CORRELATION_THRESHOLD = 0.8
HIGH_CARDINALITY_THRESHOLD = 50
MISSING_VALUE_CRITICAL_THRESHOLD = 0.5
IMBALANCE_MODERATE_RATIO = 0.3
IMBALANCE_SEVERE_RATIO = 0.1

# Visualization settings
DEFAULT_FIGSIZE = (10, 6)
HEATMAP_CMAP = 'coolwarm'
MAX_CATEGORIES_TO_PLOT = 20

# Performance settings
LARGE_DATASET_THRESHOLD = 100000  # rows
SAMPLING_SIZE = 50000
MAX_PLOT_POINTS = 10000

# UI settings
MAX_DISPLAY_COLUMNS = 50
DEFAULT_PREVIEW_ROWS = 10

# File settings
MAX_FILE_SIZE_MB = 500
SUPPORTED_ENCODINGS = ['utf-8', 'latin-1', 'cp1252', 'iso-8859-1']
SUPPORTED_SEPARATORS = [',', ';', '\t', '|']